physical entity:
  represented_as: node
  input_label: physical entity
  properties:
    name: string
process:
  represented_as: node
  input_label: process
  properties:
    name: string
physical compartment:
  represented_as: node
  input_label: compartment
  properties:
    name: string
reactant:
  represented_as: edge
  input_label: reactant
  properties:
    stoichiometry: float
product:
  represented_as: edge
  input_label: product
  properties:
    stoichiometry: float
modifier:
  represented_as: edge
  input_label: modifier
  properties: null
empty set:
  is_a: physical entity
  inherit_properties: true
  represented_as: node
  input_label: empty set
macromolecule:
  is_a: physical entity
  inherit_properties: true
  represented_as: node
  input_label: macromolecule
information macromolecule:
  is_a: macromolecule
  inherit_properties: true
  represented_as: node
  input_label: information macromolecule
necessary stimulation:
  is_a: modifier
  inherit_properties: true
  represented_as: edge
  input_label: necessary stimulation
inhibition:
  is_a: modifier
  inherit_properties: true
  represented_as: edge
  input_label: inhibition
